realx<-subset(x,(x$Date=='2/2/2007') | (x$Date=='1/2/2007'))
y<-transform(realx,Time=paste(realx$Date,realx$Time))
data<-transform(y,Time=as.POSIXct(y$Time,format='%d/%m/%Y %H:%M:%S'))
par(mfrow=c(2,2))
with(data,plot(Time,as.numeric(as.character(Global_active_power)),type='l',ylab='Global Active Power'))
with(data,plot(Time,as.numeric(as.character(Voltage)),type='l',ylab='Voltage',xlab='datetime'))
with(data,plot(Time,as.numeric(as.character(Sub_metering_1)),type='n',ylab='Energy Sub Metering',xlab=''))
with(data,points(Time,as.numeric(as.character(Sub_metering_1)),type='l'))
with(data,points(Time,as.numeric(as.character(Sub_metering_2)),type='l',col='red'))
with(data,points(Time,as.numeric(as.character(Sub_metering_3)),type='l',col='blue'))
legend('topright',legend=c('Sub_metering_1','Sub_metering_2','Sub_metering_3'),col=c('black','red','blue'),bty='n', lty=1,cex=0.8)
with(data,plot(Time,as.numeric(as.character(Global_reactive_power)),type='l',ylab='Global_reactive_power',xlab='datetime'))
dev.copy(png,file='plot4.png')
dev.off()
