x<-read.table('household_power_consumption.txt',header=TRUE,sep=';',check.names=FALSE)
realx<-subset(x,(x$Date=='2/2/2007') | (x$Date=='1/2/2007'))
y<-transform(realx,Time=paste(realx$Date,realx$Time))
with(data,plot(Time,as.numeric(as.character(Sub_metering_1)),type='n',ylab='Energy Sub Metering',xlab=''))
with(data,points(Time,as.numeric(as.character(Sub_metering_1)),type='l'))
with(data,points(Time,as.numeric(as.character(Sub_metering_2)),type='l',col='red'))
with(data,points(Time,as.numeric(as.character(Sub_metering_3)),type='l',col='blue'))
legend('topright',legend=c('Sub_metering_1','Sub_metering_2','Sub_metering_3'),col=c('black','red','blue'), lty=1)